config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :users do
    member do
      get 'profile'
      get 'matches'
    end
  end
  get 'auth/facebook/callback', to: "sessions#create"
  match 'sign_out', to: "sessions#destroy", via: :delete

  post 'create_friendship' => "friendships#create"
  delete 'delete_friendship' => "friendships#destroy"
  get 'matches/get_email' => "users#get_email"

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :friendships, dependent: :destroy
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_id", dependent: :destroy

  #From Paperclip docs
  has_attached_file :avatar,
                    :storage => :s3,  #for Amazon S3
                    :style => { :medium => "370x370", :thumb => "100x100" }

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  default_scope { order('id DESC') }

  #either find user or create a new user
  def self.sign_in_from_facebook(auth)
    find_by( provider: auth['provider'], uid: auth['uid'] ) || create_user_from_facebook(auth)
  end

  #Hash from https://github.com/mkdynamic/omniauth-facebook
  def self.create_user_from_facebook(auth)
    create(
      avatar: process_uri(auth['info']['image'] + "?width=9999"),
      email: auth['info']['email'],
      provider: auth['provider'],
      uid: auth['uid'],
      name: auth['info']['name'],
      gender: auth['extra']['raw_info']['gender'],
      date_of_birth: auth['extra']['raw_info']['birthday'],
      location: auth['info']['location'],
      bio: auth['extra']['raw_info']['bio']

      )
  end

  #Friendship Methods
  def request_match(other_user)
    self.friendships.create(friend: other_user)
  end

  def accept_match(other_user)
    self.friendships.where(friend: other_user).first.update_attribute(:state, "active")
  end

  def remove_match(other_user)
    inverse_friendship = inverse_friendships.where(user_id: other_user).first

    if inverse_friendship
      self.inverse_friendships.where(user_id: other_user).first.destroy
    else
      self.friendships.where(friend_id: other_user).first.destroy
    end

  end

  private
  def self.process_uri(uri)
    avatar_url = URI.parse(uri)
    avatar_url.scheme = 'https'
    avatar_url.to_s
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  
  # find user by sessionid if one exists and return
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
  end

  def require_login
    if session[:user_id] == nil
      redirect_to root_path
    end
  end
  #makes current_user available to entire app
  helper_method :current_user
  helper_method :require_login
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  before_action :require_login
  before_action :set_friend

  def create
    
    @inverse_friendship = current_user.inverse_friendships.where(user_id: @friend.id) #checks if inverse friendship exists

    unless @inverse_friendship.blank?
      @friend.accept_match(current_user)
      @match = true
    else
      current_user.request_match(@friend)
    end

    respond_to do |format|
      format.js
    end

  end

  def destroy
    current_user.remove_match(@friend)
    respond_to do |format|
      format.html {redirect_to users_path}
    end
  end

  private

  def set_friend
    @friend = User.find(params[:friend_id]) #global var
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      redirect_to users_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    auth = request.env["omniauth.auth"]                     #request response assigned to auth
    session[:omniauth] = auth                               #pick up that value and store it in session
    user = User.sign_in_from_facebook(auth)                 #create User passing the callback response (or locate user)
    session[:user_id] = user.id                            #create session
    redirect_to root_url, notice: "Signed In Successfully"  #redirect with message
  end

  def destroy
    session[:user_id] = nil
    session[:omniauth] = nil
    redirect_to root_url, notice: "Signed Out Successfully"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login
  before_action :set_user, only: [:edit, :profile, :update, :destroy, :get_email]
  def index
    if params[:id]
      @users = User.where('id < ?', params[:id]).limit(2)
    else
      @users = User.all.limit(2)
    end

    respond_to do |format|
      format.html
      format.js
    end

  end

  def edit
  end

  def update
    if @user.update(user_params)
      respond_to do |format|
        format.html { redirect_to users_path }
      end
    else
      redirect_to edit_user_path(@user)
    end
  end

  def destroy
    if @user.destroy
      session[:user_id] = nil
      session[:omniauth] = nil
      redirect_to root_path
    else
      redirect_to edit_user_path(@user)
    end
  end

  def profile
  end

  def matches
    #gets all friendships and grabs all friends that have active state
    @matches = current_user.friendships.where(state: "active").map(&:friend) + current_user.inverse_friendships.where(state: "active").map(&:user)
  end

  def get_email
    respond_to do |format|
      format.js
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:interest, :bio, :avatar, :location, :date_of_birth)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friendships/create.js.erb
<% if @match %>
  alert("Matched");
<% end %>

app/views/home/index.html.erb
<div class="bg-dark"></div>

<div class="home-information">
  <h1 class="slogan">Any swipe can change your life</h1>
  <%= link_to "auth/facebook", class: "btn btn-social btn-lg btn-facebook" do %>
      <i class="fa fa-facebook"></i> Sign in with Facebook
  <% end %>
  <br /><br />
</div>

<script type = "text/javascript">

jQuery(function($) {

  $.supersized({
    slide_interval   :   4000,
    transition       :   1,
    transition_speed : 700,
    slinde_links     : 'blank',

    slides           : [

      {image : '<%= image_url("bg1.jpg") %>'},
      {image : '<%= image_url("bg2.jpg") %>'},
      {image : '<%= image_url("bg3.jpg") %>'}

    ]

  });


});

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tindurr</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=0.9">
</head>
<body>

<% if current_user %>
<nav id="myNavmenu" class="navmenu navmenu-default navmenu-fixed-left offcanvas" role="navigation">

<ul class="nav navmenu-nav">
  <li class="active"><a href="#"><i class="fa fa-users"></i>Discover</a></li>

  <li class="active"><a href="#"><i class="fa fa-heart"></i>Matches</a></li>

  <li class="active"><a href="#"><i class="fa fa-cog"></i>Settings</a></li>

  <li class="active"><%= link_to 'sign_out', method: :delete do %><i class="fa fa-cog"></i>Log out<% end %></li>
</ul>

</nav>
<div class="navbar navbar-default navbar-fixed-top">
  <button type="button" class="navbar-toggle button-nav" data-toggle="offcanvas" data-target="#myNavmenu" data-canvas="body">
  <i class="fa fa-cog"></i>
  </button>
  <button type="button" class="navbar-toggle button-nav pull-right" data-toggle="offcanvas" data-target="#myNavmenu" data-canvas="body">
  <i class="fa fa-heart"></i>
  </button>

</div>
<% else %>
<a href="#" class="navbar-brand">
  <%= image_tag "logo_white.png", alt: "Tindurr Logo", class: "logo-brand" %>
</a>
<% end %>
<%= yield %>

<script type="text/javascript">
    $("#tinderslide").jTinder({
    onDislike: function (item) {
        //alert('Dislike image ' + (item.index()+1));
    },
    onLike: function (item) {
      var myId = $("#tinderslide > ul > li").last().attr("id");
      $("#user_" + myId)[0].click(); //grab link from partial
    },
    animationRevertSpeed: 200,
    animationSpeed: 400,
    threshold: 1,
    likeSelector: '.like',
    dislikeSelector: '.dislike'
});

/**
 * Set button action to trigger jTinder like & dislike.
 */
$('.actions .like, .actions .dislike').click(function(e){
  e.preventDefault();
  $("#tinderslide").jTinder($(this).attr('class'));
});
</script>

</body>
</html>

app/views/users/_match.html.erb
<tr>
  <th scope="row"><%=image_tag "#{match.avatar(:thumb)}", size: "30x30" %></th>
  <td><%= link_to match.name, profile_user_path(match.id) %></td>
  <td><%= match.updated_at.strftime('%m/%d/%Y') %></td>
  <td class="text-right">
    <%= link_to matches_get_email_path(id: "#{match.id}"), :data => {toggle: "tooltip", placement: "top"}, title: "Get Email", remote: :true do %>
      <i class="fa fa-envelope"></i>
    <% end %>
    <%= link_to delete_friendship_path(friend_id: match.id), :data => {toggle: "tooltip", placement: "top", confirm: "Are you sure?"}, title: "Unmatch", id: "delete_friendship", method: :delete do %>
    <i class="fa fa-times"></i>
    <% end %>
  </td>
</tr>

app/views/users/_user.html.erb
<li id="<%= user.id %>">
<div class="img"><%= image_tag user.avatar.url, height: '370', width: '370' %></div> 
  <div class="user-name pull-left">
    <%= link_to profile_user_path(user.id) do %><b><%= user.name %></b>, user.date_of_birth <% end %>
  </div>
    <div class="user-location text-right"><i class="fa fa-map-marker"></i><%= user.location %></div>
    <div class="like"></div>
    <div class="dislike"></div>
    <%= link_to "", create_friendship_path(friend_id: user.id), id: "user_#{user.id}", method: :post, :remote => true %>
</li>

app/views/users/edit.html.erb
<%= simple_form_for(@user, url: url_for(:action => 'update', :controller => 'users'), html: {multipart: true} ) do |f| %>

<div class="container">
  <h4 class="text-uppercase"><small>Interested in</small</h4>
  <div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
      <%= current_user.interest.capitalize %>
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
      <li role="presentation" class="dropdown-header">Interested in</li>
      <li role="presentation" class="gender"><a href="#" tabindex="-1" role="menuitem">Female</a></li>
      <li role="presentation" class="gender"><a href="#" tabindex="-1" role="menuitem">Male</a></li>
      <li role="presentation" class="gender"><a href="#" tabindex="-1" role="menuitem">Both</a></li>
    </ul>
  </div>
  <%= f.input :interest, as: :hidden, label: false %>

  <h4 class="text-uppercase"><small>Profile Description</small></h4>
  <%= f.input :bio, as: :text, label: false, :input_html => { :rows => 5, class: 'form-control' } %>

  <h4 class="text-uppercase"><small>City</small></h4>
  <%= f.input :location, label: false, :input_html => { class: 'form-control' } %>

  <h4 class="text-uppercase"><small>Age</small></h4>
  <%= f.input :date_of_birth, as: :string, label: false, :input_html => { class: 'form-control' } %>
  <br>

  <div class="text-center">
    <div class="fileinput fileinput-new" data-provides="fileinput">
      <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">
        <img data-src="holder.js/100%x100%" src="<%= current_user.avatar %>" alt="">
      </div>
      <div>
        <span class="btn btn-default btn-file"><span class="fileinput-new">Select image</span><span class="fileinput-exists">Change</span><%= f.file_field :avatar %></span>
        <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
      </div>
    </div>
  </div>

  <%= f.button :submit, class: "btn btn-primary btn-block btn-md", value: "Submit" %>
  <br />
  <%= link_to 'Cancel your account', user_path(current_user.id), method: :delete, data: { confirm: "Are you sure?" }, title: "Delete Account" %>

</div>
<% end %>


<script type="text/javascript">
//grabs text that is selected in dropdown then puts the value into the input
  $('.gender').click(function() {
    $("#dropdownMenu1").text($(this).text());
    $("#dropdownMenu1").append('<span class="caret"></span>');
    $("#user_interest").val($(this).text());
  });
</script>

app/views/users/index.html.erb
<div class="container">
  <br>
  <div class="row">
    <div class="text-center">
      <div class="wrap">

        <div id="tinderslide">
          <ul>
            <%= render @users %>
          </ul>
        </div>

        <div class="actions">
          <a href="#" class="dislike"> <i class="fa fa-times"></i></a>
          <a href="#" class="like"> <i class="fa fa-heart"></i> </a>
        </div>

      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  $("#tinderslide > ul li").tsort({attr: "id"})
</script>

app/views/users/index.js.erb
$("#tinderslide ul").append('<%= escape_javascript(render(:partial => @users, :collection => @users)) %>');
$("#tinderslide > ul > li").tsort({attr: "id"});
$("#tinderslide").jTinder();

app/views/users/matches.html.erb
<div class="container">
  
  <table class="table table-striped">
    <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Matched on</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
    <%= render partial: "match", collection: @matches %>
    </tbody>  
  </table>

</div>

<script type ="text/javascript">

$(function (){
  $('[data-toggle="tooltip"]').tooltip();
});

</script>

app/views/users/profile.html.erb
<div class="container">
  <div class="wrap">
    <div class="profile-box">
      <div class="img">
        <%= image_tag "cat.jpg", width: "100%", height: "100%" %>
      </div>

      <div class="user-name pull-left">
        <a href=""><b>Name</b>, 27</a>
      </div>

      <div class="user-location text-right">
        <i class="fa fa-map-marker"></i>London
      </div>

      <div class="description">
        <h4 class="text-uppercase"><small>Description</small></h4>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit alias, animi? Officiis, sunt, unde? Hic explicabo doloremque, reprehenderit voluptatem? Exercitationem suscipit doloribus laborum fugit modi eos libero accusamus ab mollitia.
        </p>
      </div>

    </div>
  </div>

</div>